// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGnU04CHPTASPJfNds4P7r7iitOyFiJOM',
    appId: '1:887744791735:web:5050fce9fcaba5acbab932',
    messagingSenderId: '887744791735',
    projectId: 'prepbuddy-c907a',
    authDomain: 'prepbuddy-c907a.firebaseapp.com',
    storageBucket: 'prepbuddy-c907a.firebasestorage.app',
    measurementId: 'G-RYCBKQDEP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGUoEACj_C_9sjwmq6ellbBBGqgsYUClc',
    appId: '1:887744791735:android:b42adbf7cde3bd15bab932',
    messagingSenderId: '887744791735',
    projectId: 'prepbuddy-c907a',
    storageBucket: 'prepbuddy-c907a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmyKOiWTYzGBW5gEXhiofopSMKKzCn4mQ',
    appId: '1:887744791735:ios:1b60529369851e85bab932',
    messagingSenderId: '887744791735',
    projectId: 'prepbuddy-c907a',
    storageBucket: 'prepbuddy-c907a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmyKOiWTYzGBW5gEXhiofopSMKKzCn4mQ',
    appId: '1:887744791735:ios:1b60529369851e85bab932',
    messagingSenderId: '887744791735',
    projectId: 'prepbuddy-c907a',
    storageBucket: 'prepbuddy-c907a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGnU04CHPTASPJfNds4P7r7iitOyFiJOM',
    appId: '1:887744791735:web:1af08d3a728ef799bab932',
    messagingSenderId: '887744791735',
    projectId: 'prepbuddy-c907a',
    authDomain: 'prepbuddy-c907a.firebaseapp.com',
    storageBucket: 'prepbuddy-c907a.firebasestorage.app',
    measurementId: 'G-DTN07KF1JH',
  );
}
